1
pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseGroup.java
src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseGroupRepository.java
src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpoint.java
src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEvent.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupAuditService.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupService.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseGroupAuditServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseGroupServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
src/main/java/uk/gov/ons/ctp/response/casesvc/utility/Constants.java
src/main/resources/database/changes/release-10.52.0/add_completed_by_phone_category.sql
src/main/resources/database/changes/release-10.52.0/changelog.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpointUnitTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseGroupServiceImplTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java

As a internal user (Survey administrator?)
I need to change the case response status to completed by phone for an RU for a specific CE for a specific survey
So that the respondent can complete the survey over the phone and they do not receive reminders
1. Run up ras/rm
1. Run response-operations-ui on branch `us050-manually-change-the-response-status`
1. Run ras-backstage on branch `us050a-change-response-status`
1. Build repo `rm-common-service` branch `us050a-change-response-status-completedbyphone`
1. Build rm-casesvc-api on branch `us050a-change-response-status`
1. Run rm-case-service on branch `us050a-change-response-status-completedbyphone`
1. Load data with `make setup`
1. Open http://localhost:8085/reporting-units/49900000001
1. Click change
1. See updated status …

Us050a change response status completedbyphone

---

src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.java

Added new endpoint which creates a new case with a new enrolment code for a given collection_exercise_id and ru_ref
To test, run with other PR's
[response-operations-ui](https://github.com/ONSdigital/response-operations-ui/pull/85)
[ras-backstage-service](https://github.com/ONSdigital/ras-backstage/pull/71)
[rasrm-acceptance-tests](https://github.com/ONSdigital/rasrm-acceptance-tests/pull/68)
[Trello](https://trello.com/c/FIBrMsOb/72-us051-int-generate-a-new-additional-enrolment-code-l-25pts-5d)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/227115065/US051+Provide+a+new+Enrollment+Code+to+an+RU+for+a+specific+survey+over+the+phone+Large)

Us051 generate new enrolment code

---

src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java
src/test/resources/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.Case.json

Defect 17.6, if a business had multiple enrolled respondents, when one of them completes the survey the other BI Cases are not removed from the action service and then receive reminders when they shouldn't.

Update related Bi cases when SUCCESSFUL_RESPONSE_UPLOAD event

---

src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
src/main/resources/application-cloud.yaml

- Changing `case-distribution_delay-milli-seconds` to 500. This is
required to speed up collectionExercise execution.
- Changing `createCaseEvent` logging to INFO. This is required to
investigate receipting issues without switching to DEBUG level.
- Changing `case-distribution_delay-milli-seconds` to 500 generates a
lot of noise in logs at DEBUG level. Hence, currently it is not recommended to leave
logging at DEBUG for a long time.

Performance Improvement

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseRepository.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-10.54.0/add_disable_respondent_enrolment_category.sql
src/main/resources/database/changes/release-10.54.0/changelog.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java
src/test/resources/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.Case.json
src/test/resources/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.Category.json

Added a new category `DISABLE_RESPONDENT_ENROLMENT` and added some logic to handle this event. This will transition a case to `INACTIONABLE` state and will create a new B-case if there are no remaining actionable cases and the casegroup status is not completed
Works with other PR's:
[response-operations-ui](https://github.com/ONSdigital/response-operations-ui/pull/123)
[rm-backstage](https://github.com/ONSdigital/ras-backstage/pull/96)
[ras-frontstage-api](https://github.com/ONSdigital/ras-frontstage-api/pull/60)
[ras-party](https://github.com/ONSdigital/ras-party/pull/122)
[rm-casesvc-api](https://github.com/ONSdigital/rm-casesvc-api/pull/13)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/248545529/US022+Disable+respondent+enrolment+to+a+survey) …

Us022 disable respondent enrolment

---

manifest-no-envs.yml

We need to override environmental variables at deployment time. If a
variables is specified in the manifest file it isn't being overriden.

Create a manifest file with no envs

---

src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseRepository.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java

Previously, when a respondent enrolment was disabled, we were only creating a new B case when there were no ACTIONABLE cases for the given casegroups
We actually want to create this new case when there are no ACTIONABLE BI cases
[Trello](https://trello.com/c/qPFjHpuH/195-defect-ru-respondent-does-not-receive-any-comms-when-respondents-enrolment-is-disabled-after-generating-new-enrolment-code)

Defect: No comms when respondent's enrolment is disabled after generating new enrolment code

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-10.55.0/add_no_longer_required_event.sql
src/main/resources/database/changes/release-10.55.0/changelog.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java

Added new case event category `NO_LONGER_REQUIRED` to liquibase script
[Trello](https://trello.com/c/2a1r2ZJM/105-us050d-int-manually-change-the-response-status-for-a-given-ru-survey-ce-to-no-longer-required-l)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/282132485/US050d+INT+Manually+change+the+response+status+for+a+given+RU+Survey+CE+to+No+Longer+Required+L)

Us050d change response status to no longer required

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java

In the action service if the source case for a B case is not null it is linked back to a BI case. This will fix this so all B cases should not have a source case. Tested with the disable enrolment story as this is where the defect was found.

Remove source case Id for B cases being created

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/impl/CaseNotificationPublisherImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java
src/test/resources/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.Case.json
src/test/resources/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.CaseGroup.json

When publishing actions to the rabbit queue, now include `partyId` and `exerciseId` as these are now being stored in the action.case table
Works with other PR's
[rm-casesvc-api](https://github.com/ONSdigital/rm-casesvc-api/pull/16)
[rm-action-service](https://github.com/ONSdigital/rm-action-service/pull/47)
[Trello](https://trello.com/c/RfLGapt3/62-extend-representation-of-case-in-action-service)

Send exerciseId and partyId in message to action service

---

.gitignore
Makefile
diagrams/case-group-state.puml
diagrams/case-state.puml

Added state transition diagrams for case and case group plus makefile to build svgs
No code has been changed but a Makefile has been added
```
make diagrams
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome diagrams/case-state.svg
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome diagrams/case-group-state.svg
```
Ensure diagrams can be viewed

Added case service state diagrams and means to build

---

src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-10.57.0/changelog.yml
src/main/resources/database/changes/release-10.57.0/update_eq_launch_event_to_include_b_case.sql

This change is required to allow frontstage to not use BI cases anymore and for the EQ Launch event to be triggered against the B case.
Added database changes to update EQ_Launch event category so can be used with B and BI.
Ran changes in frontstage. Attempted to access EQ survey.
[Trello] https://trello.com/c/PLkePSlW

Update EQ_LAUNCH event category to work with B cases

---

src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointIT.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.java

Add end point to get cases by partyId or sampleUnitId by params. The only use case of this at the moment is in tests to be able to get IAC codes for parties or samples. This will stop us needing to query for the IAC code.
New GET api under `/cases`
1. Run unit tests
2. hit api `/cases?partyId=<uuid>`
https://trello.com/c/SwkUMf9O/99-dev-task-7-ext-access-eq-social-survey-rh

Add end point to get cases by sampleUnitId

---

.gitignore
pom.xml
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-13/add_H_cases_to_OFFLINE_RESPONSE_PROCESSED_category.sql
src/main/resources/database/changes/release-13/changelog.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/CaseCreator.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointIT.java
src/test/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiverImplIT.java

Currently when surveys responses/cases are receipted a case event is created of the OFFLINE_RESPONSE_PROCESSED category, only 'BI' cases are currently allowed for this. We need to make 'H' cases receipt-able within the current process by allowing OFFLINE_RESPONSE_PROCESSED case events for 'H' cases.
Add a DB script to add 'H' to the oldsampleunittype column for the OFFLINE_RESPONSE_PROCESSED in the category table
make a POST request to the receipts endpoint in rm-sdx-gateway with a caseId of a H case 
to test in the docker dev environment:
- spin up all the services
- create social data by running the setup-and-execute make target in social folder in rm-tools https://github.com/ONSdigital/rm-tools/tree/master/social-test-setup
- find an actionable 'H' case 
- make a POST request curl -X …

make 'H' cases allowable for OFFLINE_RESPONSE_PROCESSED case event

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcApplication.java

Bug discovered by @ajmaddaford in CI-latest where JSON not being used for key-value pairs.
Instead of flipping logging to use JSON in a `CommandLineRunner.run()` method, we're using a `@Postconstruct` instead, which should always fire.
Run with `--spring.profiles.active=cloud` or hack the `application.yml` to set `CLOUD` logger and `useJson=true`
Related Trello card: https://trello.com/c/KNOUa0pq/349-update-logging-in-all-java-services-to-use-key-value-pairs

Init JSON logging in PostConstruct method

---

pom.xml

We are seeing strange dates being returned by the Java Spring Boot REST APIs when there is a concurrency of 3 or 4 users hammering the endpoints. The dates are sometimes completely bogus (e.g. 30 February or 31 April). This is bad.
Updated rm-common-service so it they no longer uses `static` instances of a DateFormat object shared across threads which is *not thread safe*. The new version of rm-common-service is `10.49.18`.
Bug can be reproduced by hammering collex events endpoint (e.g. `http://[host]:[port]/collectionexercises/[collex id]>/events`) and checking to make sure that a date such as the `exercise_end` date is *always* being returned as the expected correct value. This bug only occurs when there are *multiple concurrent users*.
Trello: …

New version of rm-common-service to fix DateFormat multithreading bug

---

src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseIACService.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/InternetAccessCodeSvcClientService.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseIACServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/InternetAccessCodeSvcClientServiceImpl.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseIACServiceTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/InternetAccessCodeSvcClientServiceImplTest.java

It is now possible to have multiple IACs for one case. We need to be able to disable **all** of these IACs for a disabled case event.
* Added a new method to disable all IACs for a case.
* Updated existing unit tests.
* Added unit tests.
* Remove two no longer valid unit tests
* Checkout this branch
* Run acceptance tests
* Check the acceptance test pass.
[Trello](https://trello.com/c/4ukDtQX9/216-sus006-disable-uac-when-response-status-is-changed-to-data-to-be-deleted-5)

SUS006 - Allow all IACs to be disabled for a case

---

pom.xml

We recently had to do a bug fix off an earlier release and create a jar from it in artifactory. Because of that we are out of step and the snapshot version needs updating

Update snapshot version to 10.49.22

---

pom.xml

On concourse, it skips creating the dockerfile and integration tests. When a change went in replacing one of the docker plugins, the command on RAS-deploy wasn't updated and it couldn't skip over it. This change allows the casesvc to skip the creation of the docker containers by adding an environment variable to skip the tests. A PR will be made in RAS-deploy to add the variable to the pipeline when running its tests
- Added skip to docker-compose-maven-plugin
run `mvn clean install -DdockerComposeSkip -Ddockerfile.skip  -DskipITs -Dhttp.wait.skip`and the integration tests should be skipped as well as the creation of the docker containers

Fixing docker compose file

---

migration/get-surveyid-to-collection-exercises/1_get-collection-exercises.sql
migration/get-surveyid-to-collection-exercises/3_import-temp-table.sql
migration/get-surveyid-to-collection-exercises/README.md

When testing in latest, there were a few problems with the migration scripts and instructions for copying the survey IDs out of collex and into case.
Updated the scripts and instructions in `migrations/get-surveyid-to-collection-exercises`
Follow the steps in `migration/get-surveyid-to-collection-exercises/README.md`
Trello: https://trello.com/c/Av0xoJzP/516-fix-case-survey-id-migration-scripts-instructions
Related PR: https://trello.com/c/WNaIX2HO/295-add-survey-id-to-casegroups-l

Fix migration script and instructions

---

pom.xml

The Concourse CI pipeline is failing because the Action and Case services cannot download Zipkin dependencies. The dependencies are in Artifactory, but in a repo which we have not explicitly declared in our `pom.xml`.
Added `jcenter-cache` to list of Artifactory repos in the `pom.xml`.
Run the `case-service-ci-deploy-ci` job in Concourse.
Trello: https://trello.com/c/PtK76WEN/564-fix-action-case-ci-deploy-jobs-in-concourse

Add Artifactory repo to fix Concourse CI failure

---

docker-compose.yml
pom.xml
src/main/resources/application-test.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointIT.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseIACEndpointIT.java
src/test/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiverIT.java
src/test/java/uk/gov/ons/ctp/response/casesvc/message/RabbitSpringIntegrationDLQAndRetriesIT.java

Theres an intermittent bug in the case service tests where it gets stuck attempting to contact the IAC service wiremock. This only happened occasionally so its hard to test.
- Added classrule to the wiremock
- Added a thread sleep to allow the wiremock to shutdown and wake up between tests.
- running `mvn clean install` and it passing. When testing this I had to run it constantly just in case it happened again, so you may need to keep running the tests just to be thorough. Only merge when confident you can't replicate the bug.

Fix for intermittent test failure

---

pom.xml
src/test/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiverIT.java

EQ will start sending us messages containing a party ID at some point in future, which could cause the messages to be rejected, because we're not expecting the extra element in the Rabbit message.
This PR prepares the Case service with the new version of the Case API, containing the new optional party ID element in the XSD/XML.
Bumped the version of the API we're using, which contains the new XML schema.
Run the ATs to check for no regression.
Trello: https://trello.com/c/gV6X31s2/590-prepare-case-service-for-casereceipt-messages-from-eq-containing-party-id

Bump API version

---

pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiver.java

To allow the userid to get passed from rm-sdx gateway to case service, we need to update the case receipt receiver to use the case receipt party id instead of the existing case party id.
- Changed partyid from the existing case to the case receipt
Need to run with [RM-SDX Gateway PR](https://github.com/ONSdigital/rm-sdx-gateway/pull/21)
To test this locally I send a POST request to RM-SDX Gateway at the http://localhost:8191/receipts which includes the caseid and partyid of the respondent which you can get if you debug frontstage when you click access survey for an eQ. You need to first make sure an eQ has been set to in progress before you can do this. This can be done by clicking access survey. If you look in the case events table then the partyId should be a respondent and looking at …

Updating receipt receiver to use user Id

---

src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-19/changelog.yml
src/main/resources/database/changes/release-20/add-index-to-partyid-on-case.sql
src/main/resources/database/changes/release-20/changelog.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.java

In an attempt to make the to-do page on frontstage even quicker, We've decided that adding an index  on the case table for the partyid would help increase the speed. It will also now pass in a IAC boolean so it can skip adding the iac which removes another DB calls
- Added an index on the case table for the partyId column
- Added boolean check on IAC so it can be skipped
- Run with [frontstage PR](https://github.com/ONSdigital/ras-frontstage/pull/429)
- Run the acceptance tests
- Open up the todo page and make sure everything is working such as accessing survey and completing it.
[Trello](https://trello.com/c/5xsPP92s)

Performance improvements

---

manifest-template.yml

Increase the default memory to 2G in the manifest.  The previous size of 1G was insufficient and was causing multiple app crashes.

Increase the default memory on startup to 2G

---

src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java

Users were getting a 500 error when trying to disable some enrolments this is because an exception was being thrown for a B BI case.
Removed the throw exception for the check.
Removed unnecessary test that was checking for the exception

Remove bi exception

---

src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java

There are situations where the current behaviour (disabling an enrolment invalidates outstanding IAC codes) is unwanted, so this removes it
Removed the code that did this and changed the test to match

Stopping case service from removing IACs when enrolments get disabled

---

_infra/helm/case/Chart.yaml
_infra/helm/case/templates/deployment.yaml
_infra/helm/case/values.yaml

Adds kube_dns addresses for all connecting services to allow us to have circular references

Create DNS entries for each service

---

_infra/helm/case/Chart.yaml
_infra/helm/case/templates/deployment.yaml
_infra/helm/case/values.yaml

Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)

added if-statement for variable versions

---

_infra/helm/case/templates/deployment.yaml
_infra/helm/case/values.yaml

The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)

added devRepo

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/config/ReportSettings.java
src/main/java/uk/gov/ons/ctp/response/casesvc/scheduled/ReportScheduler.java
src/main/resources/application.yml

Making report scheduler configurable to allow us to disable dynamically
Also setting ports on the application yaml to match the new `ras port-forward` command rather than `ras-rm-docker-dev`

Report scheduler is now configurable

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/case/Chart.yaml

Replacing `set-env` command in GH Actions, disabled this week for security reasons.
- https://trello.com/c/5Pj2VUx5

replace deprecated cmd in GitHub Actions

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml
_infra/helm/case/templates/deployment.yaml
_infra/helm/case/values.yaml

The case service was incorrectly configured to process only 50 cases every .5 seconds and the rabbit queue is only using a single thread as consuming threads.
changes to case distribution process count and delay and rabbit queue consuming threads. This is it now configurable as a part of the deployment.

Case service incorrectly configured

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml

During the release step tag the generated docker image as both the release version and latest.

Docker tag latest at the same time as the release

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml
docker-compose.yml
pom.xml

For the integration tests use up to date GCR images and not the old ones from docker hub
Run `mvn clean install`
N/A

GCR images for integration tests

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptPubSubSubscription.java
src/test/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiverIT.java

Set the inbound channel to OFFLINE as that what SDX gateway does. 
https://trello.com/c/AxccC3Yq/737-bug-case-service-validation-error-on-preprod

Fix GCP pub sub receipting

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptPubSubSubscription.java
src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiver.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
src/test/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptReceiverTest.java

When a SDX GCP receipt comes through via pubsub, it was throwing an error because the inboundChannel wasn't being set.
This PR fixes that by hardcoding the event category, that the inboundChannel was influencing, because it was always the same anyway

Fix pubsub receipting issue

---

_infra/helm/case/Chart.yaml
openapi.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseGroupRepository.java
src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpoint.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupService.java

The endpoint that gives casegroups for a given collection exercise id will only give you the ones in IN_PROGRESS and NOT_STARTED.  Collection exercise needed one where it would return them all regardless of state.  This PR adds that endpoint.

Add endpoint for all cases

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseActionEventRequest.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/action/ProcessCaseActionEventService.java
src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseActionEventIT.java

https://trello.com/c/9H8g3qTR/1131-bug-status-change-merge-failing-in-preprod

Renaming completed to processed status enum to match the previous data

---

README.md
_infra/helm/case/Chart.yaml
docker-compose.yml
src/main/resources/application-test.yml

The docker-compose was incorrectly sending through the  'SPRING_CLOUD_GCP_PUBSUB_EMULATORHOST' environment variable. It was using ':' instead of '='. This has been fixed now.
Redundant references to Redis in the docker-compose.yml have been removed.
I have also updated the readme as this was out of date. 
Run the command 'mvn clean install'. This will spin up docker and run the integration tests.
https://trello.com/c/3UuEbzPf/1793-use-latest-collection-exercise-version-in-case-integration-tests

Use latest collection exercise version in case integration tests

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/case/Chart.yaml

This PR updates Github actions to fix "service_account_key" has been deprecate. Replacing it with google-github-actions/auth in both main.yml and comment.yml
For main.yml check https://github.com/ONSdigital/rm-case-service/runs/7355462330?check_suite_focus=true
For comment.yml see https://github.com/ONSdigital/response-operations-ui/pull/747 on how I tested in response-operations, as it is a virtual copy bar the service I didn't repeat it here

Fix service account key deprecation

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml

Currently on a push to a PR each repo builds to latest in onsrasrm-management, however this is the default artifact for all builds when using spinnaker. This means if any change to the charts are made and a PR is created it can and will break dev for everyone. 
Check the build (Publish dev Chart) and make sure it is writing naming the artifact correctly, it should be xx-pr-xx.tgz. You can also check on GCP in ons-rasrmbs-management that the artifact was written out at the right time

Update publish dev chart

---

_infra/helm/case/Chart.yaml
_infra/helm/case/values.yaml
src/main/resources/application.yml

UKIS needs to use its own template when being used in notify email.
Deploy code to your dev environment, then add a UKIS, survey ID 144 to rOps, add a CE and make it go live. Goto the logs of case service in GCP and see that there is a log with 'sending email data to pubsub' and the case id with it. There should also be a template of 'BSNE' (for notifications) or 'BSRE' (for reminders). 
https://jira.ons.gov.uk/browse/RAS-675

RAS-675: Extend surveyIdSupportedTemplate to support UKIS

---

_infra/helm/case/Chart.yaml
pom.xml

Dependabot highlighted a security vulnerability that required jackson-databind be updated to at least version 2.13.4.2.
Deploy and run acceptance test.
[Card](https://jira.ons.gov.uk/browse/RAS-792)

updated jackson

---

_infra/helm/case/Chart.yaml
_infra/helm/case/templates/deployment.yaml

This PR adds a wait time for cloud_sql_proxy and stops verbose logging. Currently we deploy the app with a side car cloud_sql_proxy container to access the db. However when a pod is redeployed and the proxy container is sent a SIGTERM the container does not close down gracefully and will kill all connections instantly (i.e sql queries). This naturally gets passed back up the chain to the respondent who will get an error. With us currently using a default pool of 5 and overflow of 10, it means anything up to 15 respondents could get an error when we deploy a new release to prod, which ain't good.
It almost certainly is the reason we see hanging queries and spikes on rollouts in Grafana. This PR adds a term_timeout which will allow the proxy to complete it's query (at least give it 30 …

RAS-850 Cloud sql proxy term timeout and verbose

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/feedback/CaseReceipt.java

The SDS ID is required to be passed to eQ when an SDS is present and the form type(s) in question match that supplied by SDS. This PR achieves this by updating the receipting object to include the SDS id'
Refer to frontstage PR.
https://jira.ons.gov.uk/browse/RAS-872

RAS-872: Extend EQ launch claims to include sds_dataset_id if required for the form_type

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/representation/action/NotifyModel.java

Fix a bit of confusion around the following bit of code 
{{ // if not not england is england. welcome to ras-rm.
if (!NOT_ENGLAND.equals(region)) {
region = "";
}}}
rename NOT_ENGLAND so it can make more sense
https://jira.ons.gov.uk/browse/RAS-769

rename NOT_ENGLAND variable to NI_REGION_CODE 

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml

This PR replaces set-output within the .github workflow file with environment variables to fix a deprecation with set-output.
Check the github builds for any deprecation warnings and ensure the workflow works after the changes.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-915

Update set-output to environment variables

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseGroup.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupAuditService.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupService.java
src/main/resources/database/changelog-master.yml
src/main/resources/database/changes/release-36/add_timestamp_for_status_change.sql
src/main/resources/database/changes/release-36/changelog.yml
src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupServiceTest.java

There is a requirement to add a datetime for when a respondents status is changed and to display this in the Response Chasing Report. This PR includes the code change to add the timedate to the Casegroup table.
Deploy this PR and update the status of a respondent (either via Frontstage or in rOps) and click the report for the associated survey. This will show the datetime of the status change within the Casegroup table.
Check the unit tests work and that the acceptance tests still work.
For completeness, deploy https://github.com/ONSdigital/rm-reporting/pull/110 and follow it's test instructions.
https://jira.ons.gov.uk/browse/RAS-940

RAS-940: Questionnaire Completion Rate Information

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml
docker-compose-down.sh
docker-compose-up.sh
docker-compose.yml
pom.xml

This PR replaces our use of the `docker-compose-maven-plugin` as that is still using `docker-compose` that has been removed
Recreated from https://github.com/ONSdigital/rm-case-service/pull/292 with GPG signing
Check the build
[RAS-1238](https://jira.ons.gov.uk/browse/RAS-1238)

RAS-1238 Update to docker compose from docker-compose

---

_infra/helm/case/Chart.yaml
pom.xml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/sampleunitnotification/SampleUnitParent.java
src/main/java/uk/gov/ons/ctp/response/lib/common/rest/RestUtilityConfig.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseCreationServiceTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java

Unit tests weren't running as surefire plugin wasn't configured correctly. Only the failsafe integration tests were running.
Also we were seeing various warnings and one of the tests was failing when run so there are changes to resolve those.
Check the unit tests are running and passing in Github Actions and locally using `mvn clean install`. There were ~158 unit tests not running previously.

Maven surefire not running and failing test and warnings

---

.github/workflows/main.yml
_infra/helm/case/Chart.yaml

Upgrades actions/cache to v4 
Check the github actions build for sucessful use of v4
[RAS-1409](https://jira.ons.gov.uk/browse/RAS-1409)

Upgrade actions/cache to v4

---

_infra/helm/case/Chart.yaml
docker-compose.yml

PubSub emulator has been migrated from GCR to GAR
Check the tests run in GHA and locally
https://jira.ons.gov.uk/browse/RAS-1423

Use migrated GAR pubsub-emulator image

---

_infra/helm/case/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseCreationReceiver.java
src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
src/main/java/uk/gov/ons/ctp/response/lib/common/error/CTPException.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseCreationServiceTest.java
src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java

For samples over a certain size, we periodically observe case creation messages being redelivered during setting ready for live. This appears to be due to the case service not being able to process a single message quickly enough, and the redelivery for unacknowledged messages happens while cases are being created.
This results in cases in the database, and then subsequent requests for the same case, causing constraint violations, which themselves result in no ack and redelivery of the same message multiple times until deadline.
Compounding this is the Spring error exception around unexpected rollback (within a nested transaction), that buries the underlying Postgres constraint violation being raised.
The safety net being introduced by this PR means we don't simply throw the Spring …

Adding graceful handling of duplicate case creation
