ONSdigital/rm-case-service

- API.md
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcBeanMapper.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/Case.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseGroup.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseGroupStatusAudit.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseGroupStatusAuditRepository.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupAuditService.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseGroupAuditServiceImpl.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImpl.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-10.49.0/add_case_group_status_field.sql
- src/main/resources/database/changes/release-10.49.0/changelog.yml
- src/main/resources/database/changes/release-10.50.0/add_case_group_status_audit_table.sql
- src/main/resources/database/changes/release-10.50.0/changelog.yml
- src/main/resources/database/changes/release-10.51.0/changelog.yml
- src/main/resources/database/changes/release-10.51.0/update_case_group_status.sql
- src/main/resources/database/changes/release-10.52.0/changelog.yml
- src/main/resources/database/changes/release-10.52.0/constrain_case_group_status_not_null.sql
- src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseCreationServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java
- src/test/resources/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.Case.json
- src/test/resources/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointUnitTest.CaseGroup.json
- src/test/resources/uk/gov/ons/ctp/response/casesvc/service/impl/CaseServiceImplTest.CaseGroup.json
- Adds status to case group, driven by state transitions from case events. 
- Audit table for Case Group Status, for traceability of changes.
> Add caseGroupStatus

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java
Allow transition from NOT STARTED to COMPLETE.
> Release 15 hot fix

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
- src/main/resources/database/changes/release-10.52.0/add_case_event_category.sql
- src/main/resources/database/changes/release-10.52.0/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java
Add state transition from NOTSTARTED to INPROGRESS via EQ_LAUNCH event.
Dependencies:
https://github.com/ONSdigital/rm-casesvc-api/pull/10
> Us062 access eq ac006 in progress

- .travis.settings.xml
- Jenkinsfile
Jenkins polls every minute for changes
A pipeline to
1. Build and unit test the source code
1. Deploy the snapshot artifact
1. Deploy to dev CF
1. Deploy to CI CF based on user feedback
1. Create release artifact based on user feedback
1. Deploy to TEST based on user feedback
> Jenkins pipeline

- API.md
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseGroupRepository.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupService.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/impl/CaseGroupServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpointUnitTest.java
- src/test/resources/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpointUnitTest.CaseGroup.json
End point to fetch all case groups for a party uuid. Use this branch with https://github.com/ONSdigital/ras-backstage/pull/75 to test functionality.
> Get case groups for party

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/casesvc/state/CaseSvcStateTransitionManagerFactory.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/state/StateTransitionManagerUnitTest.java
merge hotfix - allow the case service to transition the case group status from "in progress" to "complete"
> Casesvc 10.49.8 hotfix

- src/main/java/uk/gov/ons/ctp/response/casesvc/config/DataSourceConfiguration.java
@Bean method'cloud' must not be private or final. This causes the app to fail start up.
Removed the final modifier.
> Remove modifier

- pom.xml
The pom has some reference redundancy and the dependecies where not organised logicaly. 
1. I have added the profile in the pom and removed from the settings. 
2. I have excluded Tomcat as embended server. 
3. JDB starter removed ( redundand ) 
4. servelt dependecy removed , is alredy included in the spring boot library . 
5. AMQP starter removed. 
6. Aggreggated all spring dependecies in one place . 
7. aggreggated all ONS dependecy . 
Run unit test . Start the application.
> reorganised dependencies , removed redundants, removed tomcat

- src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcApplication.java
Added previously deleted code back in during merge
Removed code merged by mistake
> Merge error

- src/main/resources/logback.xml
Change logger configuration for trace IDs in 'CLOUD' profile.
> Zipkin logback config

- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
Currently the case service is trying to change the actionplan of cases that have been completed and do not exist in the action service any longer. This change will stop this and only change the actionplan if the case's case group status is in progress or not started as then it should be in the action service.
Add if statement to check case group is in in progress or not started before changing action plan id and updating action.
> Only change case actionplan if case group is not started or in progress status

- src/main/resources/database/changelog-master.yml
> Bump changelog master version

- API.md
The purpose of this pull request is to add documentation for endpoints that were missing it, as well as make note of redundant endpoints.
Modified API.md file to include missing endpoints.
[Trello card](https://trello.com/c/5P25F34w)
> documented missing endpoints

- _infra/Dockerfile
- _infra/helm/templates/deployment.yaml
revert the user in the dockerfile and change image pull policy to Always for preprod testing
> add Always policy and revert dockerfile

- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/templates/service.yaml
- _infra/helm/case/values.yaml
> standarsdise db config

- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/templates/service.yaml
- _infra/helm/case/values.yaml
> install managed redis template

- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/values.yaml
> add sql proxy

- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/values.yaml
> Disable zipkin and add variable to enable

- _infra/helm/case/values.yaml
The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)
> changed service port

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
> Make dev docker tag changes

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/values.yaml
> Helm chart changes to enable or disable report

- _infra/helm/case/Chart.yaml
- _infra/spinnaker/deployment-full.json
> syncronize default helm chart

- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
- _infra/spinnaker/prodDeploy.json
Update needed to hash in production pipeline, in order to include release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141
> update SHA256 for protectedEnvTemplate in Spinnaker prodDeploy

- .github/workflows/comment.yml
- _infra/helm/case/Chart.yaml
> change from sandbox to dev

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/values.yaml
> add resource requests for the proxy container

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcBeanMapper.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/ActionTemplate.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/ActionTemplateRepository.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/ActionTemplateEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/representation/ActionTemplateDTO.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/ActionTemplateService.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-23/add-action-template-table.sql
- src/main/resources/database/changes/release-23/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/ActionTemplateEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/ActionTemplateServiceTest.java
As a part of merging actions to casesvc,
Introducing new table `action_template` with `casesvc` schema and associated mapping for action-template to case 
Introducing new table `action_template` with `casesvc` schema and associated mapping for action-template to case 
Unit test/ Integration Tests
[trello](https://trello.com/c/BtJ2nXu9/247-s23a-create-a-new-table)
> New table action template

- _infra/helm/case/Chart.yaml
> app version bump to fix master build failure

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/hpa.yaml
- _infra/helm/case/values.yaml
> add min replicas

- .github/workflows/comment.yml
- _infra/helm/case/Chart.yaml
> add key-value support for comments

- _infra/helm/case/Chart.yaml
> Urgent build failure on master due to chart version

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/message/EventPublisher.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/message/notification/CaseNotification.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/message/sampleunitnotification/SampleUnit.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/message/sampleunitnotification/SampleUnitParent.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/ctp/response/lib/dto/CaseDTO.java
- src/main/java/uk/gov/ons/ctp/response/lib/message/CaseNotification.java
- src/main/java/uk/gov/ons/ctp/response/lib/message/SampleUnit.java
- src/main/resources/casesvc/xsd/inbound/SampleUnitNotification.xsd
- src/main/resources/casesvc/xsd/outbound/caseNotification.xsd
> Active enrolment work update and build failure fix

- .github/workflows/comment.yml
- _infra/helm/case/Chart.yaml
Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action
> new action comment

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseGroupRepository.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseGroupEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupService.java
- src/main/resources/application.yml
To provide a retry logic for action event processing another endpoint was required on case to provide number of cases against the collection exerciseid
A new endpoint has been added
> Big sample retry logic

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseGroupRepository.java
> Count query update

- _infra/helm/case/Chart.yaml
> updating version to trigger master merge build

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/lib/collection/exercise/CollectionExerciseDTO.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/client/CachingTestIT.java
- src/test/resources/uk/gov/ons/ctp/response/casesvc/service/CaseCreationServiceTest.CollectionExerciseDTO.json
- src/test/resources/uk/gov/ons/ctp/response/casesvc/service/CaseGroupServiceTest.CollectionExerciseDTO.json
- src/test/resources/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.CollectionExerciseDTO.json
> Remove casetypes from collection exercise

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/CaseCreator.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseCreationServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java
> remove action plan for action changes

- README.md
- _infra/helm/case/Chart.yaml
> Remove unused badges

- _infra/helm/case/Chart.yaml
> updating build version

- _infra/helm/case/Chart.yaml
> Increase chart version

- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
> Bump app version and fix github actions

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
> Update sql-proxy from 1.16 to 1.22

- _infra/helm/case/Chart.yaml
- pom.xml
Update the version of the docker plugin
`mvn clean install`
> Latest version of docker plugin

- _infra/helm/case/Chart.yaml
- docker-compose.yml
> Bump version and add pubsub emulator variable to docker compose file to fix build

- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
> Update chart versions automatically

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseReceiptPubSubSubscription.java
> Add more logging

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/message/CaseCreationReceiver.java
- src/main/resources/application-test.yml
https://trello.com/c/126JzDkR/871-s41-implement-spring-integration-for-pubsub-between-case-service-and-action-service
> Fixing spring integration issue

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseAction.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/repository/CaseActionRepository.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-29/case_action_addition.sql
- src/main/resources/database/changes/release-29/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/domain/CaseActionRepositoryTestIT.java
- src/test/resources/delete-test-data.sql
https://trello.com/c/jLyGuULE/937-s44-create-new-view-in-case-service-and-make-spring-jpa-alignments
> Adding case action view to case in prepration of action-case merge

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/scheduled/distribution/CaseDistributor.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/scheduled/distribution/CaseDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java
https://trello.com/c/r2BEEpDV/938-s44-remove-iac-call-via-spring-integration-and-make-it-sync
> initial commit for iac case creation

- _infra/helm/case/Chart.yaml
- _infra/helm/case/values.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/client/ActionSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/scheduled/distribution/CaseDistributionScheduler.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
- src/main/resources/application-test.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseCreationServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java
https://trello.com/c/Fvaxr59z/940-activate-new-process-action-events
> feature-toggel case action service on

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
> Adding char lables for mapping

- _infra/helm/case/Chart.yaml
- _infra/helm/case/values.yaml
> Update cpu limit

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/templates/retry-failed-event.yaml
- _infra/helm/case/values.yaml
- docker-compose.yml
- src/main/java/uk/gov/ons/ctp/response/casesvc/CaseSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/config/GCP.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/domain/model/CaseActionEventRequest.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseActionEventEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/representation/action/CaseActionEvent.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/action/ProcessCaseActionEventService.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/utility/PubSubEmulator.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseActionEventIT.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/message/TestPubSubMessage.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/action/ProcessEventServiceTest.java
https://trello.com/c/qjeSODjt/964-provide-feedback-logic-for-action-via-collection-exercise
> Adding feedback logic for action event status for each run

- _infra/helm/case/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupService.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/CaseService.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-34/add_constrant_case_group.sql
- src/main/resources/database/changes/release-34/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseCreationServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseGroupServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/CaseServiceTest.java
https://trello.com/c/TYSW1DYB/1064-apply-constraint-on-case-database-to-avoid-duplicate-sample-load
> Adding constraint on case goup to avoid multiple sample upload

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/values.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/config/SurveySvc.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/representation/action/NotifyModel.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/action/email/ProcessEmailActionService.java
- src/main/java/uk/gov/ons/ctp/response/lib/party/representation/Attributes.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/action/ProcessEventServiceTestData.java
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/action/email/ProcessEmailActionServiceTest.java
https://trello.com/c/A8u90DZF/1344-make-changes-to-case-service-to-pass-form-type-as-classifiers-while-giving-a-call-to-the-notify-gateway
> making changes to support multiple templates based on form types

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
- _infra/helm/case/values.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/config/SurveySvc.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/representation/action/NotifyModel.java
- src/main/java/uk/gov/ons/ctp/response/casesvc/service/action/email/ProcessEmailActionService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/casesvc/service/action/email/ProcessEmailActionServiceTest.java
Case service changes to support for quarterly fuels survey support
https://trello.com/c/mzt8q6oH/1397-quarterly-fuels-survey-multiple-template-support
> fuel survey support for template

- .github/workflows/comment.yml
- _infra/helm/case/Chart.yaml
- pom.xml
bump jackson version to latest version fixing vulnerability
> bump jackson version to latest version

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/deployment.yaml
- src/main/java/uk/gov/ons/ctp/response/casesvc/endpoint/CaseEndpoint.java
> Upgrade cloudsqlproxy

- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions
> Fix setoutput

- _infra/helm/case/Chart.yaml
- _infra/helm/case/templates/hpa.yaml
Update autoscaling from v2beta2 to v2
The HPA change has already been proven here https://github.com/ONSdigital/ras-party/pull/389, but can be done again if required, just deploy via helm
> Update HPA to v2

- .github/CODEOWNERS
- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
- _infra/helm/case/values.yaml
- docker-compose.yml
Migrating case service from GCR to GAR.
Deploy this to your environment, setting configBranch to `ras-1405-case-gar-migration`. The deployment will hang until you replace the image in the YAML with `europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images/case:pr-296`.
[Card](https://jira.ons.gov.uk/browse/RAS-1405)
> gar migration

- .github/workflows/main.yml
Updates the push release image step to align with migration
Eyeball check, only runs on merge to main
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1405
> Fix docker push command

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/case/Chart.yaml
Pinning GHA versions to commit references
Check GHA
[RAS-1418](https://jira.ons.gov.uk/browse/RAS-1418)
**Not a production candidate**
> RAS-1418 EPIC: Unpinned tag for a non-immutable Action in workflow
